//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp20
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientResponse
    {
        public int id { get; set; }
        public int questionnaire_id { get; set; }
        public int patient_id { get; set; }
        public string response { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Questionnaire Questionnaire { get; set; }
    }
}
